### PR TITLE
#164139677 Set-up test framework

### PR DESCRIPTION
**Pull request by olajide1234**
#### What does this PR do?
Sets up Mocha with Chai and Chai-http as testing framework

#### Description of Task to be completed?
Install Mocha, Chai and Chai-http modules, include test script in package.json
#### How should this be manually tested?
- Run test with `npm run test`
- To view test report and analysis in html format, run `npm run coverage` and find html file in `mochawesome-report` file created.
#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
#164139677

#### Screenshots (if appropriate)
Not required

#### Questions:
None

### CODE REVIEW

**Review by 9jaswag — COMMENTED** [review]
@olajide1234 there are merge conflicts in PR. They need to be fixed, before they can be merged

**Comment by olajide1234** [comment]
> @olajide1234 there are merge conflicts in PR. They need to be fixed, before they can be merged

@9jaswag Thanks. I have resolved the conflict.

**Comment by 9jaswag** [comment]
@olajide1234 you have merge commits in yours

**Review by 9jaswag — APPROVED** [review]
LGTM!

**Pull request merged**
